apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{.kubernetes_cluster_name.value}}
spec:
  api:
    loadBalancer:
      type: Public
      additionalSecurityGroups: ["{{.common_http_sg_id.value}}"]
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.kops_s3_bucket.value}}/{{.kubernetes_cluster_name.value}}
  # Create one etcd member per AZ
  etcdClusters:
  - etcdMembers:
  {{range $i, $az := index .availability_zones.value 0}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
    name: main
  - etcdMembers:
  {{range $i, $az := index .availability_zones.value 0}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }} {{/* converts eu-west-1a to a */}}
  {{end}}
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.13.10
  masterPublicName: api.{{.kubernetes_cluster_name.value}}
  networkCIDR: {{.vpc_cidr_block.value}}
  networkID: {{.vpc_id.value}}
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  # Public (utility) subnets, one per AZ
  {{range $i, $id := index .public_subnet_ids.value 0}}
  - id: {{.}}
    name: utility-{{index (index $.availability_zones.value 0) $i}}
    type: Utility
    zone: {{index (index $.availability_zones.value 0) $i}}
  {{end}}
  # Private subnets, one per AZ
  {{range $i, $id := index .private_subnet_ids.value 0}}
  - id: {{.}}
    name: {{index (index $.availability_zones.value 0) $i}}
    type: Private
    zone: {{index (index $.availability_zones.value 0) $i}}
    egress: {{index $.nat_gateway_ids.value $i}}
  {{end}}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---

# Create one master per AZ
{{range index .availability_zones.value 0}}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{$.kubernetes_cluster_name.value}}
  name: master-{{.}}
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  kubernetesVersion: 1.13.10
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{.}}
---
  {{end}}

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.kubernetes_cluster_name.value}}
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  kubernetesVersion: 1.13.10
  machineType: t2.small
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  {{range index .availability_zones.value 0}}
  - {{.}}
  {{end}}
